### PR TITLE
Fixed #144 UseBasicParsing missing on Invoke-WebRequest

### LINKED ISSUE #144: UseBasicParsing missing on Invoke-WebRequest
In `Get-OctopusProject.ps1`, `Invoke-WebRequest` is missing `-UseBasicParsing` argument. As a consequence, system account cannot use the script when Internet Explorer engine is not available/configured.

This is especially the case when running a script with a system account, as it is the case with a Teamcity agent for instance.

As all octopus endpoints return JSON, I guess DOM parsing is not use so `-UseBasicParsing` could be added on all `Invoke-WebRequest` inside OctoPosh.

### PR DESCRIPTION
**Pull request by blemasle**
This should make OctoPosh usable by system accounts or when Internet Explorer is not available/configured. See #144

### CODE REVIEW

**Comment by blemasle** [comment]
What about this pull request. This forbids anyone using a local system account to use OctoPosh :(

**Comment by Dalmirog** [comment]
Hi @blemasle I was convinced I merged this already. For some reason its not letting me do it right now. Would you please branch the latest Octoposh and send back a PR? I'd do it myself but I'd like to give you the credit for it :)

**Comment by blemasle** [comment]
Sorry, I did not see the notification about your request. I'll do it right now

**Comment by blemasle** [comment]
@Dalmirog There you go :)

**Comment by brushwood24** [comment]
@Dalmirog Just a friendly reminder about this pull request.

**Pull request merged**
